# You can reference documentation on rules here https://realm.github.io/SwiftLint/rule  -directory.html
disabled_rules: # rule identifiers to exclude from running
  - closure_end_indentation
  - cyclomatic_complexity
  - discouraged_object_literal
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_length
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_return
  - large_tuple
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - prefixed_toplevel_constant
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - redundant_self_in_closure
  - redundant_string_enum_value
  - required_deinit
  - reduce_into
  - sorted_enum_cases
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unneeded_parentheses_in_closure_argument
  - todo
  - vertical_whitespace_opening_braces
  - vertical_whitespace_between_cases
  - xct_specific_matcher
  - nslocalizedstring_require_bundle
  - file_types_order
  
opt_in_rules: # some rules are only opt-in
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_todo
  - direct_return
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - implicit_getter
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - local_doc_comment
  - lower_acl_than_parent
  - mark
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - no_space_in_method_call
  - non_overridable_class_declaration
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_swiftui_state
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_void_return
  - reduce_boolean
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - superfluous_else
  - switch_case_alignment
  - syntactic_sugar
  - test_case_accessibility
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_synthesized_initializer
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_computed_property
  - weak_delegate
  - xctfail_message
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?
                    \/\/  .*?
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/(\d{2}|\d{4})\.
                    \/\/  Copyright (©|\(c\)) \d{4} .*?\. All rights reserved\.
                    \/\/

attributes:
  always_on_same_line: ["@IBAction", "@IBSegueAction", "@NSManaged", "@discardableResult", "@escaping", "@objc"]

custom_rules:
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
  custom_todo:
    name: "TODO Violation"
    regex: "(TODO).(?!.*(https&)).(?!.*issue)"
    match_kinds: comment
    message: "TODOs must include a link to the issue."
    severity: warning
